#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  1 13:54:00 2019

@author: mmhender
"""
import tensorflow as tf
slim = tf.contrib.slim
from slim.learning import train_step

def train_step_fn(sess, train_op, global_step, train_step_kwargs):
  """Function that takes a gradient step and specifies whether to stop.
      (Wrapper function for train_step in learning.py)
  Args:
    sess: The current session.
    train_op: An `Operation` that evaluates the gradients and returns the
      total loss.
    global_step: A `Tensor` representing the global training step.
    train_step_kwargs: A dictionary of keyword arguments.

  Returns:
    The total loss and a boolean indicating whether or not to stop training.

  Raises:
    ValueError: if 'should_trace' is in `train_step_kwargs` but `logdir` is not.
  """
  
  
  total_loss, should_stop = train_step(sess, train_op, global_step, train_step_kwargs)
  
  if train_step_fn.step % train_step_kwargs['val_every_n_steps']==0:
      # validate
      print('validation set accuracy:')
      
  train_step_fn.step += 1
  
  return [total_loss, should_stop]
  